### ISSUE TITLE
Library is broken

### ISSUE THREAD

**Issue by CaffeineDuck** [dahsameer/nepse-api-helper#3]
It doesn't work anymore. I'm investigating the cause, will update the issue once I find it out. 

HTML is being returned instead of authTokens when you try to hit the /auth endpoint for getting token and salts.

**Comment by dahsameer** [comment]
Someone at nepse just randomly decided that they're gonna validate headers to make sure the request is coming from their website smh. Don't they know that its possible to imitate headers. 

anyway, fixed by the commit 59c0bf2ceb7a8668e9edf89e9bc5f851fa01e7b8

**Comment by dahsameer** [comment]
Just realised that since I also changed spaces with tabs, the commit looks chaotic.
I just added a few headers in the requests which solved the issue
```
headers: {
	"User-Agent": "Mozilla/5.0",
	"Referer": "https://newweb.nepalstock.com.np/"
}
```
As for the request which gets data for security detail, the following headers were added
```
"User-Agent": "Mozilla/5.0",
"Origin": "https://newweb.nepalstock.com.np",
"Referer": `https://newweb.nepalstock.com.np/company/detail/${security.id}`,
"Referrer-Policy": "strict-origin-when-cross-origin"
```
for Referer, it requires the id of the security which we are fetching data from

**Comment by CaffeineDuck** [comment]
Hi, thanks for the quick response. Really appreciated.
